---
blank_issues_enabled: false
contact_links:
  - name: 💡 Feature Request
    url: https://github.com/jmuelbert/jmbde-java/discussions/new?category=feature-requests
    about: Suggest an improvement you’d like to see added to `jmbde-java`
  - name: FAQ
    url: https://github.com/jmuelbert/jmbde-java/wiki/FAQ
    about: You may find your question and the answer to it here.
  - name: Documentation
    url: https://jmuelbert.github.io/jmbde-java/
    about: The documentation tells you how to use jmbde-java.
  - name: GitHub Community Support
    url: https://github.com/orgs/community/discussions
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.
